# Generated by Django 2.2.12 on 2020-09-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='proyectos', verbose_name='Imágen'),
        ),
    ]
